version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "BPR:main(chore):"
    ignore:
      - dependency-name: "gradle/actions"
        versions: [ ">=6" ]
