# These are supported funding model platforms

github: [VictorGugug]
patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
custom:
