settings:
  mention_contributors_in_pull_requests:
    - "true"
  synchronize:
    paths:
      - source: spigot/src/main/resources/lang/translations_en.yml
      - source: spigot/src/main/resources/lang/translations_cs.yml
      - source: spigot/src/main/resources/lang/translations_de.yml
      - source: spigot/src/main/resources/lang/translations_es.yml
      - source: spigot/src/main/resources/lang/translations_fi.yml
      - source: spigot/src/main/resources/lang/translations_fr.yml
      - source: spigot/src/main/resources/lang/translations_hu.yml
      - source: spigot/src/main/resources/lang/translations_id.yml
      - source: spigot/src/main/resources/lang/translations_it.yml
      - source: spigot/src/main/resources/lang/translations_ja.yml
      - source: spigot/src/main/resources/lang/translations_ko.yml
      - source: spigot/src/main/resources/lang/translations_nl.yml
      - source: spigot/src/main/resources/lang/translations_pl.yml
      - source: spigot/src/main/resources/lang/translations_pt-br.yml
      - source: spigot/src/main/resources/lang/translations_ru.yml
      - source: spigot/src/main/resources/lang/translations_sk.yml
      - source: spigot/src/main/resources/lang/translations_th.yml
      - source: spigot/src/main/resources/lang/translations_tr.yml
      - source: spigot/src/main/resources/lang/translations_zh-CN.yml
      - source: spigot/src/main/resources/lang/translations_zh-TW.yml
